app = "tabula-rasa"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  build-target = "app"

[env]
  NODE_ENV = "production"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.http_checks]]
    internal = "30s"
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    restart_limit = 2
    timeout = "2s"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
